esphome:
  name: example_somfy_configuration

esp32:
  board: esp32-poe-iso
  framework:
    type: arduino

external_components:
  - source:
      type: git
      url: https://github.com/w-shackleton/esphome-somfy-cover
    components: [ somfy_cover ]
  # Or for local development:
  # - source: components

somfy_cover:
  id: somfy_remote
  gdo0: 13
  gdo2: 33
  csn: 14
  sck: 15
  mosi: 16
  miso: 32

cover:
  - platform: somfy_cover
    id: bedroom_blind
    name: Bedroom blind
    # Which remote (above) is this cover using?
    somfy_cover_hub_id: somfy_remote
    # Unique secret code for this remote
    remote_code: 0x42424242
    # Unique key for storing rolling codes in the ESP32's EEPROM
    rolling_code_key: bedroom_blind

    # Configure a "program" button to pair the blind
    program_button:
      name: Bedroom blind program
    # Some blinds need the "UpDown" button to be pressed to pair
    updown_button:
      name: Bedroom blind UpDown
